# Permalinks
permalink:        pretty

# Setup
title:            Arctic Tea Programmer
tagline:          It's warm down here...
description:      Canadian in NC...
url:              https://david-driscoll.github.io/

author:
  name:           'David Driscoll'
  url:            http://david-driscoll.github.io/

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/david-driscoll/david-driscoll.github.io

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
