markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Iced Tea Programmer
tagline:          It's warm down here... but the drinks are good!
description:      Canadian in NC...
url:              https://david-driscoll.github.io/

author:
  name:           'David Driscoll'
  url:            http://david-driscoll.github.io/

paginate:         5

# Custom vars
version:          2.0.0

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-gist
